### ISSUE TITLE
💡 [REQUEST] - <Build Giter Android V1 Project Architecture>

### ISSUE THREAD

**Issue by snack655** [COMP-IT/giter-android#1]
### Start Date

01/08/2024

### Summary
Giter V1 Android Architecture를 구축하고 실제 코드 상으로 구현합니다.
#### TODO
- [ ] 전체적인 아키텍처 구조 구성.
  - [ ] Diagram 그리기.
- [ ] Third Party Library 선별.
  - [ ] Precompiled Script Plugin 작성.
  - [ ] Gradle 정리.
 - [ ] 설계한 아키텍쳐 코드로 구현.

### Basic Example
SDD : https://www.notion.so/minjae1230/COMP-39e5429765fa4949991105ade6b0f861?pvs=4
### Unresolved questions
...
